import Head from "next/head"
import styles from "@/styles/Home.module.css"
import VendingMachine from "./VendingMachine"
import Balance from "./Balance"
import Restock from "./Restock"
import WithdrawFunds from "./WithdrawFunds"
import { useState, useEffect } from "react"
import { ethers } from "ethers"
const { Network, Alchemy, Utils } = require("alchemy-sdk")
import { ConnectButton } from "@rainbow-me/rainbowkit"

export default function Home() {
  const [userAddress, setUserAddress] = useState("")
  const [results, setResults] = useState(false)
  const [hasQueried, setHasQueried] = useState(false)
  const [account, setAccount] = useState(null)

  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>By Daryle Tan</div>
          <Balance />
          {/* <div className={styles.connectWallet}> */}
          <ConnectButton className={styles.connectWallet} />
          {/* </div> */}
        </div>

        <div className={styles.center}>
          <VendingMachine />
        </div>

        <div className={styles.grid}>
          <Restock />
          <WithdrawFunds />
        </div>
      </main>
    </>
  )
}
