import Head from "next/head"
import styles from "@/styles/Home.module.css"
import VendingMachine from "./VendingMachine"
import Balance from "./Balance"
import Restock from "./Restock"
import WithdrawFunds from "./WithdrawFunds"
import { useState, useEffect } from "react"
import { ethers } from "ethers"
import { ConnectButton } from "@rainbow-me/rainbowkit"
import abi from "../contractJson/VendingMachine.json"

export default function Home() {
  const [account, setAccount] = useState("Not Connected")
  const [state, setState] = useState({
    provider: null,
    signer: null,
    contract: null,
  })

  useEffect(() => {
    const template = async () => {
      const contractAddress = "0x87c8e40838ae5d9d86912F4A6Fbb622BBacfa72C"
      const contractABI = abi.abi

      try {
        const { ethereum } = window
        const account = await ethereum.request({
          method: "eth_requestAccounts",
        })

        window.ethereum.on("accountsChanged", () => {
          window.location.reload()
        })
        setAccount(account)
        const provider = new ethers.providers.Web3Provider(ethereum) //read from the Blockchain
        const signer = provider.getSigner() //write to the blockchain

        const contract = new ethers.Contract(
          contractAddress,
          contractABI,
          signer,
        )
        console.log(contract)
        setState({ provider, signer, contract })
      } catch (error) {
        console.log(error)
      }
    }
    template()
  }, [])

  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>By Daryle Tan</div>
          <Balance />
          <ConnectButton className={styles.connectWallet} />
        </div>

        <div className={styles.center}>
          <VendingMachine />
        </div>

        <div className={styles.grid}>
          <Restock />
          <WithdrawFunds />
        </div>
      </main>
    </>
  )
}
